### ISSUE TITLE
revoke&recreate your osu!api key

### ISSUE THREAD

**Issue by Piotrekol** [Deliay/SyncPlugin#6]
You forgot to remove it:
https://github.com/Deliay/SyncPlugin/blob/7b1c4dcb1dd8c44c777b665b639c8bc247232c93/BeatmapSuggest/Danmaku/BeatmapSuggestFilter.cs#L95
These keys aren't meant to be stored in application, but rather ask user to provide one.

**Comment by MikiraSora** [comment]
I will revoke this and nofity users provide their api key.Thx :D
